---
title: WH-BBS：煌兄の大看板（电子公告板）
minititle: WH-BBS：煌兄大看板
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: false
  steps:
    # title: Steps
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    title: 
    date: 2016-09-01 00:00:00 -0700
markdown: kramdown
highlighter: rouge
lsi: false
description: 这是一介凡人的自留地。
baseurl: "/bbs"
url: https://whing.cn
color: "#f2f2f2"
